### ISSUE TITLE
Magento 2.4.2 came with a new configuration "Catalog media URL format" that is not explained yet

### ISSUE THREAD

**Issue by hostep** [magento/merchdocs#1111]
# Bug report

## Description

Hi folks

Magento 2.4.2 came with a new configuration called "Catalog media URL format", which can be found in: Stores > Configuration > General > Web > Url Options

The configurations description has a link to the documentation so we can get more information about what it's purpose is and links to: https://docs.magento.com/user-guide/configuration/general/web.html#url-options

However this new option is not explained yet on that page.

I don't quite understand what the configuration purpose is or what option I should pick, so some kind of explanation would be appreciated 🙂 

Thanks!

### Steps to reproduce

1. Install Magento 2.4.2
1. Go to Stores > Configuration > General > Web > Url Options
1. Notice the option "Catalog media URL format" and click the link "Learn more" in its description
<img width="1104" alt="Screenshot 2021-03-25 at 15 08 54" src="https://user-images.githubusercontent.com/85479/112487472-050b7f00-8d7d-11eb-9db0-5cded0b166aa.png">

## Expected result

Finding useful information about this new configuration on https://docs.magento.com/user-guide/configuration/general/web.html#url-options

## Possible solutions

Somebody will need to figure out what this configuration does and then write documentation for it

## Magento release version

- [x] >= 2.4.2

**Comment by dobooth** [comment]
@ZhovnirMaria @EvheniiaKolkhiieva, care to take a shot at this one?

**Comment by EvheniiaKolkhiieva** [comment]
@dobooth yes of course :)

**Comment by EvheniiaKolkhiieva** [comment]
@magento I am working on this

**Comment by dobooth** [comment]
Fixed in PR above.

**Comment by hostep** [comment]
@dobooth: [as discussed](https://github.com/magento/merchdocs/pull/1230#issuecomment-834477972) with @shrielenee this is not fully fixed yet, can you please reopen this? Thanks!

**Comment by EvheniiaKolkhiieva** [comment]
Hi @hostep Do not worry about this, I remember about our discussion and will open a separate PR, for this, it is not necessary to open this ticket again 😊

**Comment by hostep** [comment]
@EvheniiaKolkhiieva: ok great! Can you tag me in it? Because I still don't understand the difference between the two options and I want to know what they mean, thanks! 🙂

**Comment by EvheniiaKolkhiieva** [comment]
For sure @hostep ☺️

**Comment by hostep** [comment]
Hi @EvheniiaKolkhiieva, have you found any time yet to try to improve this documentation?

@dobooth or @shrielenee  we really need to keep this ticket open, otherwise it will be forgotten I'm afraid.

Copy paste from [my earlier remark](https://github.com/magento/merchdocs/pull/1230#issuecomment-827128270) about what is still missing:
> However, I think that it is still unclear with the current proposition, maybe you could:
>
> - provide an example for both options
> - provide more explanation of why one would pick one option over the other as to explain what the benefit would be of one option versus the other

**Comment by shrielenee** [comment]
Please let us know the status of your efforts @EvheniiaKolkhiieva! Thanks @hostep 💯

**Comment by EvheniiaKolkhiieva** [comment]
Hi @hostep and @shrielenee , you are totally right. I have created a new issue https://github.com/magento/merchdocs/issues/1421 , so as not to forget this implementation. I will deal with this shortly
Thanks
